name: build-gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run build script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git checkout -B gh-pages
          ./scripts/build_pages.sh
          git add -A
          git commit -m 'build pages'
          git push -fu origin gh-pages
